### ISSUE TITLE
Android : app has to be restarted to notice the change of system language

### ISSUE THREAD

**Issue by nibo** [Jesway/flutter_translate#20]
I have to restart the android app to notice the system language change. On ios the app will be automatically rebuild.

Any ideas to solve this?

**Comment by bratan** [comment]
@nibo - Basically the system locale is only retrieved/used during the application initialization.

Changes to the system locale while the application is running are not currently detected on Android. 

On iOS, as you mentioned, the app is rebuilt so the new locale is picked up during initialization.

I`m going to implement this behavior for Android as well, in the near future.

Until then, you could use the [ACTION_LOCALE_CHANGED](https://developer.android.com/reference/android/content/Intent.html#ACTION_LOCALE_CHANGED) intent to detect the locale change and select the new locale if supported.

**Comment by bratan** [comment]
Moved to https://github.com/bratan/flutter_translate/issues/21
