### ISSUE TITLE
change Locale lang in app lunch (main method)

### ISSUE THREAD

**Issue by mohafouad** [Jesway/flutter_translate#25]
i saved current lang in SharedPreferences key
when app start i get this key and want to set this as my current local

i tray with main method

>  String currentLang=await AppUtil.currentLang();
  var delegate = await LocalizationDelegate.create(
      fallbackLocale:currentLang !=null && currentLang != "" ? currentLang : 'en_US',
      supportedLocales: ['en_US', 'ar']);

but not work as expected

**Comment by bratan** [comment]
This is not the correct way to do this. Please see [saving/restoring the selected locale](https://github.com/bratan/flutter_translate/wiki/2.-Automatically-saving-&-restoring-the-selected-locale) for an example.

The ```fallbackLocale``` is only used for fallback, not for actually changing the locale.
