### ISSUE TITLE
Do you know an app, extension or similar to create and update all json files in a simpler way than manually?

### ISSUE THREAD

**Issue by basketball-ico** [Jesway/flutter_translate#28]

**Comment by bratan** [comment]
@basketball-ico - I`m using https://www.codeandweb.com/babeledit and it works pretty good.

**Comment by basketball-ico** [comment]
It looks good, but the license is paid :(, you don't know any alternative?

**Comment by bratan** [comment]
No, sorry.

**Comment by nohli** [comment]
@basketball-ico 

This plugin uses the Google Translate API to generate Json files in other languages:
https://marketplace.visualstudio.com/items?itemName=esskar.vscode-flutter-i18n-json

I switched to flutter_translate though.
