### ISSUE TITLE
title and bottom navigation bar item not translate after setting local success.

### ISSUE THREAD

**Issue by liudonghua123** [Jesway/flutter_translate#38]
I have a page which contains some bottom navigationbar item and in one page, I set the locale and the strings of current page changed except the appbar title and bottom navigationbar items. I have to click any of the navigationbar item, then it changed.
I simplify the code and make a demo on https://github.com/liudonghua123/redux_thunk_example/tree/flutter_translate.

It seems the same as using another translate package (easy_localization, https://github.com/aissat/easy_localization/issues/108).

**Comment by liudonghua123** [comment]
Finally, I modified the following code to fix this.
change `changeLocale` `async`, and in its implementation await `delegate.changeLocale`.
```dart
void changeLocale(BuildContext context, String localeCode) async
{
	if (localeCode != null)
	{
		await LocalizedApp.of(context).delegate.changeLocale(localeFromString(localeCode));

		LocalizationProvider.of(context).state.onLocaleChanged();
	}
}
```

And before dispatch local action, await changeLocale finish.
```dart
                await changeLocale(
                    context, '${locale.languageCode}_${locale.countryCode}');
                StoreProvider.of<AppState>(context)
                    .dispatch(LocaleAction(locale));
```

**Comment by Mohamed-Rashed** [comment]
not work with me
