### ISSUE TITLE
How to mock the library in widget tests?

### ISSUE THREAD

**Issue by VytorCalixto** [Jesway/flutter_translate#48]
When testing a widget the `_translations` map is passed as null and throws a exception. It's possible to wrap the widget in a `LocalizedApp` widget and configure the localization, but I believe that testing a single widget should be more straightforward. Am I missing something here?

Example error:
```
The following NoSuchMethodError was thrown building ExpiredProductButton(dirty):
The method 'containsKey' was called on null.
Receiver: null
Tried calling: containsKey("mission")
```

**Comment by xzhorikx** [comment]
I've just spent two hours configuring all the required things, but I've made the following approach:

1. Create a simple service class that would have a transaltion method (i.e. `String safeTranslate(String key)`).
2. Use DI/Service Locator to get said service in class
3. Call `safeTranslate(key)` every time I need a translation


**Example:**
1. Creating `TranslateService`

I use[ `get_it`](https://github.com/fluttercommunity/get_it) and [`injectable`](https://pub.dev/packages/injectable) as a service locator in my app.
```
import 'package:flutter_translate/flutter_translate.dart' as globalTranslate;
import 'package:injectable/injectable.dart';

/// Implementation that is registered in GetIt service locator
@RegisterAs(TranslateService)
@injectable
class TranslateServiceImpl implements TranslateService {
  @override
  String safeTranslate(String key) {
    try{
      return globalTranslate.translate(key);
    } catch(Exception){
      return "translation.error";
    }
  }
}

/// Abstract translate service
abstract class TranslateService {
  String safeTranslate(String key);
}
```

2. Use DI/Service locator in tested class

At this point, you need to configure `GetIt` - go through their tutorials on pages linked above and all should be safe and sound. Two notes that are not mentioned in tutorials:

* Make sure to add `test/**` source folder in `build.yaml`
* run `flutter packages pub run build_runner watch test` once configured to generate test dependencies

```
import 'package:get_it/get_it.dart';
...

/// Class that will be tested
class TestedClass {
  /// Instance of TranslateService that is provided by GetIt (service locator)
  final TranslateService _translateService = GetIt.instance.get();
  
  // Some method that uses translation
  String doSomeStuff() {
    return _translateService.safeTranslate("translation_key")
  }
}
```

3. Testing a class that requires translation

* Create `your_class_test.dart` file under `test` folder
```
/// Important: GetIt needs to be initialized in a top level function
@injectableInit
void configureInjection(String environment) =>
    $initGetIt(GetIt.instance, environment: environment);

void main() {

  configureInjection("Some env value");

  FlutterTest.test("Date formatter: today date", (){
    /// Translation service should be located once class is created
    final TestedClass testedClass  = TestedClass();
    String safeTranslation = testedClass.doSomeStuff(); <--- no exception here
    ...
  });
```

**Comment by IlyaMax** [comment]
@VytorCalixto you can call `Localization.load(<String,dynamic>{});` before tests and error won't be thrown
