### ISSUE TITLE
Support for more plural formats

### ISSUE THREAD

**Issue by SredzinskiPatryk** [Jesway/flutter_translate#54]
In many languages you have different forms of words depending on number of items.

Currently flutter_translate does only support:
"0"
"1"
"else"

can you please add other forms of plurals: "many", "few" etc?

for example:
in English you'd say:
0 department`s`, 1 department, 2+ department`s`

but in Polish you'd say:
0 dzia`łów`, 1 dzia`ł`, 2-4 dzia`ły`, 5 dzia`łów`, 11 dzia`łów`, 12 dzia`łów`, 13 dzia`łów`, 22 dzia`ły`

So you have different versions for 2-4, 22-24, 32-34, 42-44 and so on (yeah weird)
But such cases are in many other languages as well

Native flutter supports all these: https://api.flutter.dev/flutter/intl/Intl/plural.html

https://developer.mozilla.org/en-US/docs/Mozilla/Localization/Localization_and_Plurals

**Comment by vladimirandroid** [comment]
@SredzinskiPatryk I forked flutter_translate and flutter_translate_gen and modified plurals to work like native Intl. Actually I used native Intl inside.
@bratan Yo, man. Your translate tool is really great! Please take a look at my forks to take my changes to your repos. I really don't want to support my forks )))

https://github.com/vladimirandroid/flutter_translate_gen
https://github.com/vladimirandroid/flutter_translate

@SredzinskiPatryk to make my forks work you can use git dependencies:
https://flutter.dev/docs/development/packages-and-plugins/using-packages#dependencies-on-unpublished-packages

BUT!!! It is better to copy all the code to your project and use path dependencies. I'm not sure that I let my forks live )

**Comment by marinat** [comment]
@vladimirandroid could you please make PR for this?

**Comment by ekuleshov** [comment]
@bratan if #79 PR is acceptable I can also check @vladimirandroid changes for flutter_translate_gen plugin. Thanks.
