### ISSUE TITLE
Add support for Desktop (MacOS and Windows)

### ISSUE THREAD

**Issue by MyBuzzTechnologies** [Jesway/flutter_translate#60]
I use your latest version in our app (flutter_translate: ^1.6.0) but can't build for macOS or Windows due to lack of support by your package.

With the new release of Flutter 2.0.0 where desktop support is in beta and possibly stable channels, support for desktop is really important.

**Comment by bratan** [comment]
@MyBuzzTechnologies -  I've added support for desktop with example for windows in v2.0
