### ISSUE TITLE
Version resolving failed for plugin_platform_interface

### ISSUE THREAD

**Issue by intkhabahmed** [Jesway/flutter_translate#61]
Issue: This package depends on flutter_device_locale 0.4.0 which depends on plugin_platform_interface version 1.0.1 which is very old as there is version 2.0.0 available. So when I am trying to add crashlytics to my project which has the latest 2.0.0 version as dependency, the version resolving is getting failed. Please fix this as soon as possible.

**Comment by bratan** [comment]
The flutter_device_locale dependency was removed in the latest version so you shouldn't have this issue anymore.
