### ISSUE TITLE
Null safety?

### ISSUE THREAD

**Issue by rgbinnovation** [Jesway/flutter_translate#67]
Hi, have plan to add null safety to this package soon? It is preventing me from upgrading. Thanks!

**Comment by erperejildo** [comment]
This still blocking me. Can we know at least when will this be updated?

**Comment by rafaelsetragni** [comment]
I did the conversion to null-safety. I've already submitted a pull request to this plugin developer.

[Pull request: Migration to Null-safety](https://github.com/bratan/flutter_translate/pull/70)

**Comment by rafaelsetragni** [comment]
I did a new one, more simple to merge, without so much improvement.

[Pull request: More simple null safety migration](https://github.com/bratan/flutter_translate/pull/71)

**Comment by bratan** [comment]
Implemented in https://github.com/bratan/flutter_translate/pull/71
