### ISSUE TITLE
Cut / Copy / Paste buttons

### ISSUE THREAD

**Issue by hanyska** [Jesway/flutter_translate#68]
![IMG_20210428_083726](https://user-images.githubusercontent.com/32494180/116357919-5c2dc500-a7fd-11eb-95f7-376231b88ce1.jpg)

I have Polish language turned on, but the buttons are in English

```
var delegate = await LocalizationDelegate.create(
    fallbackLocale: 'pl',
    supportedLocales: ['pl'],
  );

  runApp(LocalizedApp(delegate, MyApp()));
```

and 

```
@override
Widget build(BuildContext context) {
  var localizationDelegate = LocalizedApp.of(context).delegate;
  .....

   localizationsDelegates: [
    GlobalMaterialLocalizations.delegate,
    GlobalWidgetsLocalizations.delegate,
    GlobalCupertinoLocalizations.delegate,
    localizationDelegate
  ],
  supportedLocales: localizationDelegate.supportedLocales,
  locale: localizationDelegate.currentLocale,
}
```

**Comment by porfirioribeiro** [comment]
Those buttons are related with the Operative System, Android in that case.
The translation comes from your OS settings, you need to put your OS in Polish

This is nothing to do with flutter_translate or flutter itself

**Comment by bratan** [comment]
@hanyska - I`m not sure what could be the issue here. If you add a TextField or a CupertinoTextField to the example application you can see that the translations are applied correctly to the menu.

> Those buttons are related with the Operative System, Android in that case.
> The translation comes from your OS settings, you need to put your OS in Polish
> 
> This is nothing to do with flutter_translate or flutter itself

This is not correct, the localization should work regardless of the OS language selection.

**Comment by porfirioribeiro** [comment]
@bratan You are right, i misunderstood it

**Comment by LiuMentz** [comment]
Hello, can you share your solution please?
