### ISSUE TITLE
How can I use localization files from the Document folder?

### ISSUE THREAD

**Issue by maksym-ostrovyj-ew** [Jesway/flutter_translate#72]
Hello. I try to use another path for my localization files 

 var delegate = await LocalizationDelegate.create(
      ...
        basePath: '/data/user/0/com.example.app/app_flutter/i18Sources/'
      ...
       supportedLocales: [
           'en_EN',
           'pt_PT',
           'pt_BR',
      ]

but I still have this Unhandled Exception: Unable to load asset: /data/user/0/com.example.app/app_flutter/i18Sources/en.json

Is there any way to use localization files outside of the assets folder?

**Comment by bratan** [comment]
@kabazyba - The assets need to be located within the assets bundle, there is no other alternative for now.
