### ISSUE TITLE
[ERROR:flutter/lib/ui/ui_dart_state.cc(207)] Unhandled Exception: Unable to load asset: assets/i18n/en.json

### ISSUE THREAD

**Issue by xmartinez22** [Jesway/flutter_translate#73]
I keep receiving this message when i run my program. if i add 
flutter:
  assets:
   - assets/i18n
  
then i receive message No file or variants found for asset: assets/i18n.

**Comment by bratan** [comment]
Make sure the assets are outside the `lib `folder. 

If the assets are located within the `lib `folder, you need to specify the path as `lib/assets/i18n`.

**Comment by xmartinez22** [comment]
i had to manually create the assets/i18n because it didn't exist. why would it not exist? how do i get these files in there? also yes they are outside the lib folder

**Comment by xmartinez22** [comment]
nevermind i thought the app was to auto translate it for you but you have to specify the translation yourself?

**Comment by bratan** [comment]
Yes.
