### ISSUE TITLE
Get list from translation file

### ISSUE THREAD

**Issue by erperejildo** [Jesway/flutter_translate#74]
I have a dynamic list showing some descriptions like this:

```
List<Map> descriptions = [
"title":  "My title",
"description": ["description1", "description2"]
];
```

How could I get this from the translation json file?

**Comment by bratan** [comment]
You can to create a list of localization keys (for descriptions) instead and then for each item you can get the value using the translate method.

**Comment by erperejildo** [comment]
Thanks, that worked

**Comment by erperejildo** [comment]
you mean something like this?
`["translation.text", "translation.another_text"]`

Because if I do that I will need to modify the widget every time I change the translations json. That list should pick as many translations as I have automatically

**Comment by bratan** [comment]
The package doesn't support this functionality so you need to implement yourself.

**Comment by ezamagni-tg** [comment]
This feature would have been implemented by #45 
Sadly, the author rejected it

**Comment by Skogsfrae** [comment]
> The package doesn't support this functionality so you need to implement yourself.

@bratan I once implemented it myself and proposed it as an improvement (very useful for other people too as I can see) with PR https://github.com/bratan/flutter_translate/pull/45 that was rejected :)

I was told that to include a new translation I had to make a new build anyway, which is true, but edit the codebase (which in some flows requires a PR) is way different than just pressing a button to make a new build with an automation environment that downloads the updated translated strings (Ex.: Bitrise.io).

**Comment by erperejildo** [comment]
I opened it since more people requested the same thing.

@bratan let me explain a real example here:
I have a screen with information about changes from latest version. It looks like this:

![Screenshot_1627484325](https://user-images.githubusercontent.com/5629919/127345428-a3eb707b-644c-4b96-8db7-30d46380862b.png)

This bullet points or sections are dynamic, based on what info I need to display. Right now, if I want to update this I need to modify the translations files and with this, the length of my list. We could eliminate the second change if we can pick automatically the length of the translations.

When you say "This problem can easily be solved by creating an array of localization keys instead", it's true, but with that PR we can easily forget about that.

And I have the same situation in many places, so it's not "very situational".
