### ISSUE TITLE
Slight difference in font size for different locale

### ISSUE THREAD

**Issue by danielchan303** [Jesway/flutter_translate#75]
I notice the font size of the Text change a little bit when I am changing locale from en to zh_HK on iOS. The font is smaller in en comparing to zh_HK. 

Even the text that is not translate behave like this. For example 'Hello', is bigger when my locale is set to zh_HK and become smaller when changing locale to en.

Any ideas?

**Comment by bratan** [comment]
Probably a font/rendering issue, you need to ask this question here: https://github.com/flutter/flutter/issues
